# Generated by Django 6.0.1 on 2026-01-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid - Awaiting Payment'), ('PENDING', 'Pending - Payment Processing'), ('PAID', 'Paid - Payment Successful'), ('FAILED', 'Failed - Payment Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNPAID', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of all items before shipping', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Final total amount charged', max_digits=10)),
                ('is_gift', models.BooleanField(default=False)),
                ('gift_message', models.TextField(blank=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, help_text='Stripe Payment Intent ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='Which tenant/client owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('variant_name', models.CharField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='unit_price * quantity', max_digits=10)),
                ('product_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.booking')),
                ('product', models.ForeignKey(blank=True, help_text='Reference to product (may be deleted later)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('tenant', models.ForeignKey(help_text='Which tenant/client owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Booking Item',
                'verbose_name_plural': 'Booking Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='payments_bo_tenant__c90fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'customer_email'], name='payments_bo_tenant__821aff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'created_at'], name='payments_bo_tenant__908333_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['tenant', 'booking'], name='payments_bo_tenant__b28382_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['tenant', 'product'], name='payments_bo_tenant__b14158_idx'),
        ),
    ]
