# Generated by Django 6.0.1 on 2026-01-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'client-a', 'acme-corp')", max_length=100, unique=True)),
                ('domain', models.CharField(help_text="Domain or subdomain (e.g., 'clienta.com' or 'clienta.yourdomain.com')", max_length=255, unique=True)),
                ('business_name', models.CharField(blank=True, help_text='Public-facing business name', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
