# Generated by Django 6.0.1 on 2026-05-16 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0002_alter_service_options_service_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('selected_areas', models.JSONField(default=list)),
                ('quantities', models.JSONField(default=dict)),
                ('carpets', models.JSONField(default=dict)),
                ('appliances', models.JSONField(default=dict)),
                ('furnished_status', models.CharField(blank=True, max_length=50)),
                ('parking', models.CharField(blank=True, max_length=50)),
                ('biohazard', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentlink', models.URLField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'session_id'], name='services_cl_tenant__43fbca_idx'), models.Index(fields=['customer_email'], name='services_cl_custome_2dcb5a_idx')],
            },
        ),
    ]
