# Generated by Django 6.0.1 on 2026-05-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0003_cleaningbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='cleaningbooking',
            name='services_cl_tenant__43fbca_idx',
        ),
        migrations.RemoveIndex(
            model_name='cleaningbooking',
            name='services_cl_custome_2dcb5a_idx',
        ),
        migrations.AddField(
            model_name='bookingsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingsnapshot',
            unique_together={('tenant', 'session_id')},
        ),
    ]
