# Generated by Django 6.0.1 on 2026-05-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_bookingsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningbooking',
            name='property_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cleaningbooking',
            name='selected_datetime',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('timeslot', models.CharField(blank=True, help_text="Leave blank to block the entire day. Otherwise, type the exact slot to block (e.g., '09:00 - 12:00').", max_length=50)),
                ('reason', models.CharField(blank=True, help_text='e.g., Bank Holiday, Fully Booked, etc.', max_length=200)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'timeslot')},
            },
        ),
    ]
