# Generated by Django 5.2.9 on 2026-07-17 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0005_cleaningbooking_property_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Actual time spent on the job', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='cleaning_booking',
            field=models.ForeignKey(blank=True, help_text='Reference to the original cleaning booking (wizard data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='services.cleaningbooking'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='complaint_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='complaint_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='complaint_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the job was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='has_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private admin notes'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date and time payment was received', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Stripe transaction ID or reference', max_length=255),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid_cash', 'Paid (Cash)'), ('paid_card', 'Paid (Card)'), ('paid_bank', 'Paid (Bank Transfer)')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='1-5 star rating from customer', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='reschedule_history',
            field=models.JSONField(blank=True, default=list, help_text='List of {from, to, reason} objects'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='rescheduled_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the booking was rescheduled'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='review_request_sent',
            field=models.BooleanField(default=False, help_text='Whether a review request email was sent to the customer'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the review request was sent', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='tax_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['payment_status', 'payment_date'], name='services_se_payment_ec5eba_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['status', 'completed_at'], name='services_se_status_ec6433_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['has_complaint'], name='services_se_has_com_2a7975_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['rating'], name='services_se_rating_1b5eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['review_request_sent'], name='services_se_review__65e580_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['utm_source', 'utm_medium'], name='services_se_utm_sou_7a9a08_idx'),
        ),
    ]
