# Generated by Django 5.2.9 on 2026-07-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicebooking_actual_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='phone',
            field=models.CharField(blank=True, help_text='Customer phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='property_details',
            field=models.JSONField(blank=True, default=dict, help_text='Address, postcode, etc.'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='selected_datetime',
            field=models.JSONField(blank=True, default=dict, help_text='Raw booking date and time slot'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time of the booking', null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Start time of the booking', null=True),
        ),
    ]
