# Generated by Django 5.2.9 on 2026-07-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicebooking_phone_servicebooking_property_details_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicebooking',
            name='services_se_review__65e580_idx',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='review_request_sent',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='review_requested_at',
        ),
        migrations.AddField(
            model_name='cleaningbooking',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('sms', 'SMS'), ('call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('instagram_dm', 'Instagram DM'), ('email', 'Email'), ('other', 'Other')], help_text='How the booking was received (e.g., website, WhatsApp, etc.)', max_length=20, null=True),
        ),
    ]
