# Generated by Django 5.2.9 on 2026-07-19 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=255)),
                ('notification_type', models.CharField(choices=[('arrival', 'Provider Arrival Alert'), ('completion', 'Job Completion Notice'), ('review', 'Feedback Request')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_success', models.BooleanField(default=True)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
