# Generated by Django 5.2.9 on 2026-07-20 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
