# Generated by Django 6.0.1 on 2026-01-27 22:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief description for product cards', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Your cost (for profit calculations)', max_digits=10, null=True)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price (shows discount percentage)', max_digits=10, null=True)),
                ('discount_type', models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_start_date', models.DateTimeField(blank=True, null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (unique per tenant)', max_length=50)),
                ('barcode', models.CharField(blank=True, help_text='UPC/EAN/ISBN barcode', max_length=100)),
                ('track_inventory', models.BooleanField(default=True, help_text='Track stock levels?')),
                ('allow_backorders', models.BooleanField(default=False, help_text='Allow purchase when out of stock?')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'summer, sale, featured')", max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Main product image')),
                ('video_url', models.URLField(blank=True, help_text='Product video (YouTube/Vimeo)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage/featured section?')),
                ('is_digital', models.BooleanField(default=False, help_text='Digital product (no shipping)?')),
                ('requires_shipping', models.BooleanField(default=True, help_text='Does this product need shipping?')),
                ('is_taxable', models.BooleanField(default=True, help_text='Apply tax to this product?')),
                ('has_variants', models.BooleanField(default=False, help_text='Does this product have size/color variants?')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title (leave blank to use product name)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0, help_text='Total units sold')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='Which tenant/client owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Coupon code (e.g., 'SUMMER2024')", max_length=50)),
                ('description', models.CharField(blank=True, help_text='Internal description', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed_amount', 'Fixed Amount Off'), ('free_shipping', 'Free Shipping'), ('buy_x_get_y', 'Buy X Get Y')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('applies_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Categories'), ('products', 'Specific Products')], default='all', max_length=20)),
                ('categories', models.CharField(blank=True, help_text='Comma-separated category names', max_length=500)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required', max_digits=10)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total times this code can be used (null = unlimited)', null=True)),
                ('usage_limit_per_customer', models.PositiveIntegerField(default=1, help_text='Times each customer can use this code')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='How many times this code has been used')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Which tenant/client owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Image URL (S3/Cloudinary)')),
                ('alt_text', models.CharField(blank=True, help_text='SEO alt text', max_length=200)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Use as main product image?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('tenant', models.ForeignKey(help_text='Which tenant/client owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1_name', models.CharField(default='Size', help_text="e.g., 'Size', 'Color', 'Material'", max_length=50)),
                ('option1_value', models.CharField(help_text="e.g., 'Large', 'Blue', 'Cotton'", max_length=100)),
                ('option2_name', models.CharField(blank=True, help_text='Optional second attribute', max_length=50)),
                ('option2_value', models.CharField(blank=True, max_length=100)),
                ('option3_name', models.CharField(blank=True, help_text='Optional third attribute', max_length=50)),
                ('option3_value', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Variant-specific image (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('tenant', models.ForeignKey(help_text='Which tenant/client owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'option1_value'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review headline', max_length=200)),
                ('content', models.TextField(help_text='Review text')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Did they actually buy this?')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by admin?')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='How many found this helpful')),
                ('image_url', models.URLField(blank=True, help_text='Customer photo (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('tenant', models.ForeignKey(help_text='Which tenant/client owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='products_pr_tenant__7042ce_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'sku'], name='products_pr_tenant__832bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'slug'], name='products_pr_tenant__24ea68_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='products_pr_tenant__85d2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_featured'], name='products_pr_tenant__df2996_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False), models.Q(('sku', ''), _negated=True)), fields=('tenant', 'sku'), name='unique_sku_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['tenant', 'code'], name='products_di_tenant__6209b7_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['tenant', 'is_active'], name='products_di_tenant__2f2461_idx'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_discount_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['tenant', 'product', 'position'], name='products_pr_tenant__d9c142_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'product'], name='products_pr_tenant__7a0c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'sku'], name='products_pr_tenant__dedc6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'option1_value', 'option2_value', 'option3_value'), name='unique_variant_combination'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', 'product', 'is_approved'], name='products_re_tenant__c080d2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', 'rating'], name='products_re_tenant__1e42c1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='products_re_created_7e194a_idx'),
        ),
    ]
